AWSTemplateFormatVersion: "2010-09-09"

Resources:
  MySG:
    Type: AWS::EC2::SecurityGroup
    DeletionPolicy: Retain
    Properties:
      GroupDescription: "Allow SSH"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: MySG
  
  MyEBS:
    Type: AWS::EC2::Volume
    DeletionPolicy: Snapshot
    Properties:
      Size: 1
      AvailabilityZone: us-east-1a
      VolumeType: gp2
      Tags:
        - Key: Name
          Value: MyEBS